-- ============================================================
-- RALLY ROW-LEVEL SECURITY
-- ============================================================
-- Run AFTER schema.sql and functions.sql. Enables RLS on every rally_
-- table and installs org-scoped, role-aware policies.
--
-- Model (maps to rbac.js roles):
--   viewer  (rank 1) : read-only across the org
--   rep     (rank 2) : create records; edit rows they own; edit child
--                      rows (line items, tasks, ...) in their org
--   manager (rank 3) : edit / delete ANY row in the org
--   admin   (rank 4) : everything, including users, roles, config
--
-- Enforcement primitives (functions.sql):
--   rally_is_member(org)   -> boolean
--   rally_role_rank(org)   -> int (0 non-member .. 4 admin)
--
-- The repetitive policies are generated by DO loops over three table
-- groups so the file stays legible and every table gets a consistent,
-- correct policy set. Special tables (orgs, users, memberships, mailboxes,
-- notifications, audit) are handled explicitly afterward.
-- ASCII only, no em-dash / en-dash.
-- ============================================================

-- ------------------------------------------------------------
-- 0. Enable RLS on all rally_ tables
-- ------------------------------------------------------------
do $$
declare t text;
begin
  for t in
    select table_name from information_schema.tables
    where table_schema = 'public'
      and table_name like 'rally_%'
      and table_name <> 'rally_waitlist'   -- pre-existing table, not part of this schema
  loop
    execute format('alter table %I enable row level security;', t);
    execute format('alter table %I force row level security;', t);
  end loop;
end;
$$;

-- ------------------------------------------------------------
-- 1. OWNED business tables  (org_id + owner_id)
--    SELECT : any member
--    INSERT : rep+ , and the new row must be owned by the creator
--             unless the creator is manager+ (who may assign owners)
--    UPDATE : manager+ , OR rep who owns the row
--    DELETE : manager+
-- ------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'rally_companies','rally_contacts','rally_deals','rally_activities',
    'rally_quotes','rally_leads',
    'rally_projects','rally_saved_views'
  ]
  loop
    execute format('drop policy if exists %I on %I;', t||'_sel', t);
    execute format('drop policy if exists %I on %I;', t||'_ins', t);
    execute format('drop policy if exists %I on %I;', t||'_upd', t);
    execute format('drop policy if exists %I on %I;', t||'_del', t);

    execute format($f$
      create policy %I on %I for select
        using ( rally_is_member(org_id) );
    $f$, t||'_sel', t);

    execute format($f$
      create policy %I on %I for insert
        with check (
          rally_role_rank(org_id) >= 3
          or ( rally_role_rank(org_id) >= 2
               and (owner_id is null or owner_id = auth.uid()) )
        );
    $f$, t||'_ins', t);

    execute format($f$
      create policy %I on %I for update
        using (
          rally_role_rank(org_id) >= 3
          or ( rally_role_rank(org_id) >= 2 and owner_id = auth.uid() )
        )
        with check ( rally_is_member(org_id) );
    $f$, t||'_upd', t);

    execute format($f$
      create policy %I on %I for delete
        using ( rally_role_rank(org_id) >= 3 );
    $f$, t||'_del', t);
  end loop;
end;
$$;

-- ------------------------------------------------------------
-- 2. CHILD / detail tables  (org_id, no direct owner)
--    Line items, stakeholders, tasks, subitems, join tables, etc.
--    SELECT : any member
--    WRITE  : rep+ (a rep working a deal edits its line items / tasks)
--    DELETE : rep+
-- ------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'rally_deal_contacts','rally_deal_line_items','rally_deal_stakeholders',
    'rally_deal_competitors','rally_deal_close_plan',
    'rally_quote_lines','rally_quote_events',
    'rally_project_groups','rally_tasks','rally_task_assignees','rally_subitems',
    'rally_field_values'
  ]
  loop
    execute format('drop policy if exists %I on %I;', t||'_sel', t);
    execute format('drop policy if exists %I on %I;', t||'_write', t);

    execute format($f$
      create policy %I on %I for select
        using ( rally_is_member(org_id) );
    $f$, t||'_sel', t);

    execute format($f$
      create policy %I on %I for all
        using ( rally_role_rank(org_id) >= 2 )
        with check ( rally_role_rank(org_id) >= 2 );
    $f$, t||'_write', t);
  end loop;
end;
$$;

-- ------------------------------------------------------------
-- 3. CONFIG / shared tables  (org-wide, admin/manager owned)
--    Catalog, marketing, automation, pipeline + rbac config.
--    SELECT : any member
--    WRITE  : manager+ (fields.js / rbac.js gate the UI further)
--    Custom-field + role config is admin-sensitive; we require manager+
--    at the DB floor and let the app's can() calls tighten to admin.
-- ------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'rally_products','rally_campaigns','rally_sequences','rally_invoices',
    'rally_automations','rally_automation_runs',
    'rally_pipeline_stages','rally_custom_fields',
    'rally_role_grants','rally_field_security'
  ]
  loop
    execute format('drop policy if exists %I on %I;', t||'_sel', t);
    execute format('drop policy if exists %I on %I;', t||'_write', t);

    execute format($f$
      create policy %I on %I for select
        using ( rally_is_member(org_id) );
    $f$, t||'_sel', t);

    execute format($f$
      create policy %I on %I for all
        using ( rally_role_rank(org_id) >= 3 )
        with check ( rally_role_rank(org_id) >= 3 );
    $f$, t||'_write', t);
  end loop;
end;
$$;

-- ------------------------------------------------------------
-- 4. AUDIT LOG  (append-only)
--    SELECT : audit.view is a manager+/admin capability -> manager+
--    INSERT : any member (writers + the audit trigger append)
--    UPDATE / DELETE : nobody (no policy => denied)
-- ------------------------------------------------------------
drop policy if exists rally_audit_sel on rally_audit_log;
drop policy if exists rally_audit_ins on rally_audit_log;
create policy rally_audit_sel on rally_audit_log for select
  using ( rally_role_rank(org_id) >= 3 );
create policy rally_audit_ins on rally_audit_log for insert
  with check ( rally_is_member(org_id) );

-- ------------------------------------------------------------
-- 4b. TICKETS  (owned by the assignee, not an owner_id)
--    SELECT : any member
--    INSERT : rep+
--    UPDATE : manager+ , OR the assigned rep
--    DELETE : manager+
-- ------------------------------------------------------------
drop policy if exists rally_tickets_sel on rally_tickets;
drop policy if exists rally_tickets_ins on rally_tickets;
drop policy if exists rally_tickets_upd on rally_tickets;
drop policy if exists rally_tickets_del on rally_tickets;
create policy rally_tickets_sel on rally_tickets for select
  using ( rally_is_member(org_id) );
create policy rally_tickets_ins on rally_tickets for insert
  with check ( rally_role_rank(org_id) >= 2 );
create policy rally_tickets_upd on rally_tickets for update
  using ( rally_role_rank(org_id) >= 3 or (rally_role_rank(org_id) >= 2 and assignee_id = auth.uid()) )
  with check ( rally_is_member(org_id) );
create policy rally_tickets_del on rally_tickets for delete
  using ( rally_role_rank(org_id) >= 3 );

-- ------------------------------------------------------------
-- 5. ORGS
--    SELECT : members of the org
--    INSERT : any authenticated user may create a workspace (they become
--             its admin via the membership insert that follows)
--    UPDATE : admin of that org
--    DELETE : admin of that org
-- ------------------------------------------------------------
drop policy if exists rally_orgs_sel on rally_orgs;
drop policy if exists rally_orgs_ins on rally_orgs;
drop policy if exists rally_orgs_upd on rally_orgs;
drop policy if exists rally_orgs_del on rally_orgs;
create policy rally_orgs_sel on rally_orgs for select
  using ( rally_is_member(id) );
create policy rally_orgs_ins on rally_orgs for insert
  with check ( auth.uid() is not null );
create policy rally_orgs_upd on rally_orgs for update
  using ( rally_role_rank(id) >= 4 ) with check ( rally_role_rank(id) >= 4 );
create policy rally_orgs_del on rally_orgs for delete
  using ( rally_role_rank(id) >= 4 );

-- ------------------------------------------------------------
-- 6. USERS  (profiles)
--    A user always sees + edits their own profile. Members can see the
--    profiles of people they share an org with (for owner pickers, etc).
--    Only self can update a profile row.
-- ------------------------------------------------------------
drop policy if exists rally_users_sel on rally_users;
drop policy if exists rally_users_self_upd on rally_users;
drop policy if exists rally_users_self_ins on rally_users;
create policy rally_users_sel on rally_users for select
  using (
    id = auth.uid()
    or exists (
      select 1 from rally_memberships m1
      join rally_memberships m2 on m1.org_id = m2.org_id
      where m1.user_id = auth.uid() and m2.user_id = rally_users.id
    )
  );
create policy rally_users_self_ins on rally_users for insert
  with check ( id = auth.uid() );
create policy rally_users_self_upd on rally_users for update
  using ( id = auth.uid() ) with check ( id = auth.uid() );

-- ------------------------------------------------------------
-- 7. MEMBERSHIPS
--    SELECT : you see your own memberships, and admins/managers see the
--             full roster of their orgs.
--    INSERT : the org creator's first membership (making themselves admin)
--             is allowed when no membership exists yet for that org;
--             otherwise only an admin of the org may add members.
--    UPDATE / DELETE : admin of the org (cannot be your own last admin row
--             is enforced in app logic).
--    NOTE: to avoid RLS recursion, these policies never reference
--    rally_memberships directly. They go through the SECURITY DEFINER
--    helpers (rally_role_rank, rally_org_has_members) which read the table
--    with the function owner's rights and bypass RLS.
-- ------------------------------------------------------------
drop policy if exists rally_memberships_sel on rally_memberships;
drop policy if exists rally_memberships_ins on rally_memberships;
drop policy if exists rally_memberships_upd on rally_memberships;
drop policy if exists rally_memberships_del on rally_memberships;

create policy rally_memberships_sel on rally_memberships for select
  using (
    user_id = auth.uid()
    or rally_role_rank(org_id) >= 3
  );

create policy rally_memberships_ins on rally_memberships for insert
  with check (
    -- bootstrap: first ever membership for a brand-new org, created by the
    -- same user, as an admin
    ( user_id = auth.uid()
      and role = 'admin'
      and not rally_org_has_members(org_id) )
    -- or an existing admin inviting someone
    or rally_role_rank(org_id) >= 4
  );

create policy rally_memberships_upd on rally_memberships for update
  using ( rally_role_rank(org_id) >= 4 )
  with check ( rally_role_rank(org_id) >= 4 );

create policy rally_memberships_del on rally_memberships for delete
  using ( rally_role_rank(org_id) >= 4 );

-- ------------------------------------------------------------
-- 8. MAILBOXES  (per user, private)
--    Only the owning user (and org admins) can see or manage a mailbox.
--    Secrets never leave the server anyway (vault ref only).
-- ------------------------------------------------------------
drop policy if exists rally_mailboxes_sel on rally_mailboxes;
drop policy if exists rally_mailboxes_write on rally_mailboxes;
create policy rally_mailboxes_sel on rally_mailboxes for select
  using ( user_id = auth.uid() or rally_role_rank(org_id) >= 4 );
create policy rally_mailboxes_write on rally_mailboxes for all
  using ( user_id = auth.uid() )
  with check ( user_id = auth.uid() and rally_is_member(org_id) );

-- ------------------------------------------------------------
-- 9. NOTIFICATIONS  (per user)
--    You see and mark-read your own notifications. Any member of the org
--    may create one (e.g. notify_owner action targeting a teammate).
-- ------------------------------------------------------------
drop policy if exists rally_notifications_sel on rally_notifications;
drop policy if exists rally_notifications_ins on rally_notifications;
drop policy if exists rally_notifications_upd on rally_notifications;
drop policy if exists rally_notifications_del on rally_notifications;
create policy rally_notifications_sel on rally_notifications for select
  using ( user_id = auth.uid() );
create policy rally_notifications_ins on rally_notifications for insert
  with check ( rally_is_member(org_id) );
create policy rally_notifications_upd on rally_notifications for update
  using ( user_id = auth.uid() ) with check ( user_id = auth.uid() );
create policy rally_notifications_del on rally_notifications for delete
  using ( user_id = auth.uid() or rally_role_rank(org_id) >= 4 );

-- ============================================================
-- END rls.sql
-- ============================================================
