// Canonical Activity field registry (spec Section 1.9 - one table, type
// discriminates; combined rows split into individual fields = 52).
import { f, sec } from './util.js';

export const ACTIVITY_FIELDS = [
  ...sec('Core', [
    f('type', 'Type', 'picklist', { picklist: 'activityType', defaultVisible: true }),
    f('subject', 'Subject', 'text', { required: true, defaultVisible: true }),
    f('body', 'Body', 'richtext'),
    f('status', 'Status', 'picklist', { picklist: 'taskStatus' }),
    f('done', 'Done', 'boolean', { defaultVisible: true }),
    f('priority', 'Priority', 'picklist', { picklist: 'taskPriority' }),
    f('dueAt', 'Due', 'datetime', { defaultVisible: true }),
    f('completedAt', 'Completed at', 'datetime', { computed: true }),
    f('ownerId', 'Assigned to', 'user', { defaultVisible: true }),
    f('relatedType', 'Related to (type)', 'picklist', { options: ['Contact', 'Company', 'Deal', 'Ticket', 'Project', 'Quote'] }),
    f('relatedId', 'Related record', 'link', { linkTarget: 'any' }),
    f('companyId', 'Company', 'link', { linkTarget: 'company', computed: true }),
    f('contactIds', 'Contacts', 'link', { linkTarget: 'contact', multi: true }),
    f('isSystem', 'System-logged', 'boolean', { computed: true, storeKey: 'system' }),
    f('reminderAt', 'Reminder', 'datetime'),
    f('tags', 'Tags', 'tags'),
  ]),
  ...sec('Meeting', [
    f('startAt', 'Starts', 'datetime'),
    f('endAt', 'Ends', 'datetime'),
    f('durationMinutes', 'Duration (minutes)', 'number'),
    f('isAllDay', 'All day', 'boolean'),
    f('location', 'Location', 'text'),
    f('videoCallUrl', 'Video call link', 'url'),
    f('attendeeContactIds', 'Attendees (contacts)', 'link', { linkTarget: 'contact', multi: true }),
    f('attendeeUserIds', 'Attendees (team)', 'user', { multi: true }),
    f('showAs', 'Show as', 'picklist', { options: ['Busy', 'Free', 'Out of office'] }),
    f('isPrivate', 'Private', 'boolean'),
    f('meetingOutcome', 'Meeting outcome', 'picklist', { picklist: 'meetingOutcome' }),
  ]),
  ...sec('Call', [
    f('callDirection', 'Call direction', 'picklist', { options: ['Inbound', 'Outbound', 'Internal'] }),
    f('callDurationSeconds', 'Call duration (seconds)', 'number'),
    f('callOutcome', 'Call outcome', 'picklist', { picklist: 'callOutcome' }),
    f('recordingUrl', 'Recording URL', 'url'),
    f('transcript', 'Transcript', 'textarea', { computed: true }),
    f('callSummary', 'Call summary', 'textarea', { computed: true }),
    f('phoneNumber', 'Phone number', 'phone'),
  ]),
  ...sec('Email', [
    f('emailDirection', 'Email direction', 'picklist', { options: ['Sent', 'Received', 'Logged'] }),
    f('fromAddress', 'From', 'email'),
    f('toAddresses', 'To', 'email', { multi: true }),
    f('ccAddresses', 'Cc', 'email', { multi: true }),
    f('emailSubject', 'Email subject', 'text'),
    f('openedAt', 'Opened at', 'datetime', { computed: true }),
    f('openCount', 'Open count', 'number', { computed: true }),
    f('clickedAt', 'Clicked at', 'datetime', { computed: true }),
    f('clickCount', 'Click count', 'number', { computed: true }),
    f('repliedAt', 'Replied at', 'datetime', { computed: true }),
    f('threadId', 'Thread id', 'text', { computed: true }),
    f('templateId', 'Email template', 'link', { linkTarget: 'emailTemplate' }),
    f('sequenceId', 'Sequence', 'link', { linkTarget: 'sequence', computed: true }),
    f('sequenceStep', 'Sequence step', 'number', { computed: true }),
  ]),
  ...sec('Recurrence', [
    f('recurrenceRule', 'Recurrence rule (RRULE)', 'text'),
    f('recurrenceParentId', 'Recurrence parent', 'link', { linkTarget: 'activity' }),
    f('recurrenceEndsAt', 'Recurrence ends', 'date'),
    f('regenerateMode', 'Regenerate mode', 'picklist', { options: ['None', 'After due', 'After done'] }),
  ]),
  ...sec('Source', [
    f('loggedVia', 'Logged via', 'picklist', { options: ['Manual', 'Email sync', 'Calendar sync', 'Dialer', 'API', 'Sequence', 'Import'], computed: true }),
    f('externalId', 'External id', 'text', { computed: true }),
  ]),
];
