// Canonical Company field registry (spec Section 1.2 - 94 fields in 8 sections).
import { f, sec } from './util.js';

export const COMPANY_FIELDS = [
  ...sec('Identity', [
    f('name', 'Company name', 'text', { required: true, defaultVisible: true }),
    f('domain', 'Domain', 'text', { defaultVisible: true }),
    f('additionalDomains', 'Additional domains', 'text', { multi: true }),
    f('website', 'Website', 'url'),
    f('logoUrl', 'Logo URL', 'url'),
    f('legalName', 'Legal name', 'text'),
    f('tradestyle', 'Tradestyle (DBA)', 'text'),
    f('tickerSymbol', 'Ticker symbol', 'text'),
    f('isPublic', 'Publicly traded', 'boolean'),
    f('ownership', 'Ownership', 'picklist', { picklist: 'ownership' }),
    f('foundedYear', 'Founded year', 'number'),
    f('description', 'Description', 'textarea'),
    f('aboutUs', 'About us', 'textarea'),
    f('quickContext', 'Quick context', 'richtext'),
  ]),
  ...sec('Classification', [
    f('industry', 'Industry', 'picklist', { picklist: 'industry', defaultVisible: true }),
    f('industryGroup', 'Industry group', 'picklist', { options: [] }),
    f('categories', 'Categories', 'multiPicklist', { options: [] }),
    f('sicCode', 'SIC code', 'text'),
    f('sicDescription', 'SIC description', 'text'),
    f('naicsCode', 'NAICS code', 'text'),
    f('naicsDescription', 'NAICS description', 'text'),
    f('companyType', 'Company type', 'picklist', { picklist: 'companyType' }),
    f('lifecycleStage', 'Lifecycle stage', 'status', { picklist: 'lifecycleStage', defaultVisible: true }),
    f('leadStatus', 'Lead status', 'picklist', { picklist: 'leadStatus' }),
    f('rating', 'Rating', 'picklist', { picklist: 'rating' }),
    f('icpTier', 'ICP tier', 'picklist', { options: ['Ideal', 'Good fit', 'Poor fit'] }),
    f('isTargetAccount', 'Target account', 'boolean'),
    f('accountNumber', 'Account number', 'text'),
    f('site', 'Site (location label)', 'text'),
  ]),
  ...sec('Scale', [
    f('employees', 'Employees', 'number'),
    f('employeeRange', 'Employee range', 'picklist', { picklist: 'employeeRange', storeKey: 'size', defaultVisible: true }),
    f('annualRevenue', 'Annual revenue', 'currency'),
    f('revenueRange', 'Revenue range', 'picklist', { picklist: 'revenueRange' }),
    f('estimatedArr', 'Estimated ARR', 'picklist', { picklist: 'revenueRange' }),
    f('totalMoneyRaised', 'Total money raised', 'currency'),
  ]),
  ...sec('Reach', [
    f('phone', 'Phone', 'phone'),
    f('fax', 'Fax', 'phone'),
    f('email', 'Email (generic inbox)', 'email'),
    f('linkedinUrl', 'LinkedIn URL', 'url'),
    f('twitterHandle', 'Twitter / X handle', 'text'),
    f('facebookUrl', 'Facebook URL', 'url'),
    f('timezone', 'Timezone', 'picklist', { options: [] }),
    f('techStack', 'Tech stack', 'multiPicklist', { options: [] }),
  ]),
  ...sec('Addresses', [
    f('billingStreet', 'Billing street', 'text'),
    f('billingStreet2', 'Billing street 2', 'text'),
    f('billingCity', 'Billing city', 'text'),
    f('billingState', 'Billing state', 'text'),
    f('billingStateCode', 'Billing state code', 'picklist', { options: [] }),
    f('billingPostalCode', 'Billing postal code', 'text'),
    f('billingCountry', 'Billing country', 'text'),
    f('billingCountryCode', 'Billing country code', 'picklist', { options: [] }),
    f('billingLatitude', 'Billing latitude', 'number'),
    f('billingLongitude', 'Billing longitude', 'number'),
    f('shippingStreet', 'Shipping street', 'text'),
    f('shippingCity', 'Shipping city', 'text'),
    f('shippingState', 'Shipping state', 'text'),
    f('shippingPostalCode', 'Shipping postal code', 'text'),
    f('shippingCountry', 'Shipping country', 'text'),
  ]),
  ...sec('Hierarchy and relationships', [
    f('parentCompanyId', 'Parent company', 'link', { linkTarget: 'company' }),
    f('childCompaniesCount', 'Child companies', 'rollup', { computed: true }),
    f('relatedCompanyIds', 'Related companies', 'link', { linkTarget: 'company', multi: true }),
    f('territoryId', 'Territory', 'link', { linkTarget: 'territory' }),
  ]),
  ...sec('Health and ownership', [
    f('health', 'Health', 'picklist', { picklist: 'health', defaultVisible: true }),
    f('healthReason', 'Health reason', 'text'),
    f('ownerId', 'Owner', 'user', { defaultVisible: true }),
    f('ownerAssignedAt', 'Owner assigned at', 'datetime', { computed: true }),
    f('teamId', 'Team', 'link', { linkTarget: 'team' }),
    f('sharedUserIds', 'Shared users', 'user', { multi: true }),
    f('followerIds', 'Followers', 'user', { multi: true }),
    f('visibility', 'Visibility', 'picklist', { picklist: 'visibility' }),
    f('tags', 'Tags', 'tags'),
    f('isPriority', 'Priority record', 'boolean'),
  ]),
  ...sec('Engagement and rollups', [
    f('lastActivityAt', 'Last activity', 'datetime', { computed: true }),
    f('lastContactedAt', 'Last contacted', 'datetime', { computed: true }),
    f('nextActivityAt', 'Next activity', 'datetime', { computed: true }),
    f('firstInteractionAt', 'First interaction', 'datetime', { computed: true }),
    f('connectionStrength', 'Connection strength', 'picklist', { options: ['Strong', 'Medium', 'Weak'], computed: true }),
    f('contactsCount', 'Contacts count', 'rollup', { computed: true }),
    f('dealsCount', 'Deals count', 'rollup', { computed: true }),
    f('openDealsCount', 'Open deals', 'rollup', { computed: true }),
    f('wonDealsCount', 'Won deals', 'rollup', { computed: true }),
    f('lostDealsCount', 'Lost deals', 'rollup', { computed: true }),
    f('totalRevenue', 'Total revenue', 'currency', { computed: true }),
    f('recentDealAmount', 'Recent deal amount', 'currency', { computed: true }),
    f('recentDealClosedAt', 'Recent deal closed', 'datetime', { computed: true }),
    f('firstContactCreatedAt', 'First contact created', 'datetime', { computed: true }),
    f('firstDealCreatedAt', 'First deal created', 'datetime', { computed: true }),
    f('daysToClose', 'Days to close', 'number', { computed: true }),
    f('openTicketsCount', 'Open tickets', 'rollup', { computed: true }),
    f('becameCustomerAt', 'Became customer at', 'datetime', { computed: true }),
    f('originalSource', 'Original source', 'picklist', { picklist: 'leadSource', computed: true }),
    f('latestSource', 'Latest source', 'picklist', { picklist: 'leadSource', computed: true }),
    f('pageViewsCount', 'Page views', 'number', { computed: true }),
    f('formSubmissionsCount', 'Form submissions', 'number', { computed: true }),
  ]),
];
