// Canonical Contact field registry (spec Section 1.1 - 135 fields in 10
// sections, plus the 6 lead-block extras from Section 1.4 that live on the
// contact). System audit tail (id/createdAt/updatedAt/...) is implicit on
// every object and not enumerated per spec.
import { f, sec } from './util.js';

export const CONTACT_FIELDS = [
  ...sec('Identity', [
    f('salutation', 'Salutation', 'picklist', { options: ['Mr.', 'Ms.', 'Mx.', 'Dr.', 'Prof.'] }),
    f('firstName', 'First name', 'text', { required: true, defaultVisible: true }),
    f('middleName', 'Middle name', 'text'),
    f('lastName', 'Last name', 'text', { defaultVisible: true }),
    f('suffix', 'Suffix', 'text'),
    f('nickname', 'Nickname', 'text'),
    f('pronouns', 'Pronouns', 'picklist', { options: ['she/her', 'he/him', 'they/them', 'other'] }),
    f('genderIdentity', 'Gender identity', 'picklist', { options: [] }),
    f('birthdate', 'Birthdate', 'date'),
    f('avatarUrl', 'Avatar URL', 'url'),
  ]),
  ...sec('Work', [
    f('title', 'Title', 'text', { defaultVisible: true }),
    f('department', 'Department', 'text'),
    f('departmentGroup', 'Department group', 'picklist', { options: [] }),
    f('seniority', 'Seniority', 'picklist', { options: ['C-level', 'VP', 'Director', 'Manager', 'Individual contributor'] }),
    f('employmentRole', 'Employment role', 'picklist', { options: [] }),
    f('companyId', 'Company', 'link', { linkTarget: 'company', defaultVisible: true }),
    f('companyName', 'Company name (free text)', 'text'),
    f('additionalCompanyIds', 'Additional companies', 'link', { linkTarget: 'company', multi: true }),
    f('reportsToId', 'Reports to', 'link', { linkTarget: 'contact' }),
    f('assistantName', 'Assistant name', 'text'),
    f('assistantPhone', 'Assistant phone', 'phone'),
  ]),
  ...sec('Reach', [
    f('email', 'Email', 'email', { defaultVisible: true }),
    f('secondaryEmail', 'Secondary email', 'email'),
    f('workEmail', 'Work email', 'email'),
    f('emailDomain', 'Email domain', 'text', { computed: true }),
    f('phone', 'Phone', 'phone', { defaultVisible: true }),
    f('mobilePhone', 'Mobile phone', 'phone'),
    f('homePhone', 'Home phone', 'phone'),
    f('otherPhone', 'Other phone', 'phone'),
    f('fax', 'Fax', 'phone'),
    f('linkedinUrl', 'LinkedIn URL', 'url'),
    f('twitterHandle', 'Twitter / X handle', 'text'),
    f('facebookUrl', 'Facebook URL', 'url'),
    f('instagramHandle', 'Instagram handle', 'text'),
    f('otherUrls', 'Other URLs', 'url', { multi: true }),
    f('messagingHandle', 'Messaging handle', 'text'),
    f('websiteUrl', 'Website URL', 'url'),
    f('timezone', 'Timezone', 'picklist', { options: [] }),
    f('preferredLanguage', 'Preferred language', 'picklist', { options: [] }),
    f('preferredChannel', 'Preferred channel', 'picklist', { options: ['Email', 'Phone', 'SMS', 'LinkedIn'] }),
  ]),
  ...sec('Address', [
    f('mailingStreet', 'Mailing street', 'text'),
    f('mailingStreet2', 'Mailing street 2', 'text'),
    f('mailingCity', 'Mailing city', 'text'),
    f('mailingState', 'Mailing state', 'text'),
    f('mailingStateCode', 'Mailing state code', 'picklist', { options: [] }),
    f('mailingPostalCode', 'Mailing postal code', 'text'),
    f('mailingCountry', 'Mailing country', 'text'),
    f('mailingCountryCode', 'Mailing country code', 'picklist', { options: [] }),
    f('mailingLatitude', 'Mailing latitude', 'number'),
    f('mailingLongitude', 'Mailing longitude', 'number'),
    f('otherStreet', 'Other street', 'text'),
    f('otherCity', 'Other city', 'text'),
    f('otherState', 'Other state', 'text'),
    f('otherPostalCode', 'Other postal code', 'text'),
    f('otherCountry', 'Other country', 'text'),
  ]),
  ...sec('Status and qualification', [
    f('lifecycleStage', 'Lifecycle stage', 'status', { picklist: 'lifecycleStage', defaultVisible: true }),
    f('leadStatus', 'Lead status', 'picklist', { picklist: 'leadStatus' }),
    f('leadSource', 'Lead source', 'picklist', { picklist: 'leadSource' }),
    f('leadSourceDetail', 'Lead source detail', 'text'),
    f('leadScore', 'Lead score', 'number'),
    f('likelihoodToClose', 'Likelihood to close', 'percent', { computed: true }),
    f('priorityTier', 'Priority tier', 'picklist', { options: ['Tier 1', 'Tier 2', 'Tier 3'] }),
    f('rating', 'Rating', 'picklist', { picklist: 'rating' }),
    f('persona', 'Persona', 'picklist', { options: [] }),
    f('buyingRole', 'Buying role', 'multiPicklist', { picklist: 'buyingRole' }),
    f('unqualifiedReason', 'Unqualified reason', 'picklist', { picklist: 'unqualifiedReason' }),
    f('qualifiedAt', 'Qualified at', 'datetime', { computed: true }),
    f('becameCustomerAt', 'Became customer at', 'datetime', { computed: true }),
    // Lead-block extras (Section 1.4) - live on the contact, single-entity model.
    f('scoreBreakdown', 'Score breakdown', 'json', { computed: true }),
    f('assignedVia', 'Assigned via', 'picklist', { options: ['Rule', 'Round-robin', 'Manual'], computed: true }),
    f('firstCampaignId', 'First campaign', 'link', { linkTarget: 'campaign' }),
    f('estimatedValue', 'Estimated value (pre-deal)', 'currency'),
    f('expectedCloseDate', 'Expected close date (pre-deal)', 'date'),
    f('isArchived', 'Archived', 'boolean'),
  ]),
  ...sec('Ownership and system', [
    f('ownerId', 'Owner', 'user', { defaultVisible: true }),
    f('ownerAssignedAt', 'Owner assigned at', 'datetime', { computed: true }),
    f('teamId', 'Team', 'link', { linkTarget: 'team' }),
    f('sharedUserIds', 'Shared users', 'user', { multi: true }),
    f('followerIds', 'Followers', 'user', { multi: true }),
    f('visibility', 'Visibility', 'picklist', { picklist: 'visibility' }),
    f('tags', 'Tags', 'tags', { defaultVisible: true }),
    f('isPriority', 'Priority record', 'boolean'),
    f('isUnworked', 'Unworked', 'boolean', { computed: true }),
  ]),
  ...sec('Consent and privacy', [
    f('emailOptOut', 'Email opt-out', 'boolean'),
    f('doNotCall', 'Do not call', 'boolean'),
    f('smsOptOut', 'SMS opt-out', 'boolean'),
    f('marketingStatus', 'Marketing status', 'picklist', { picklist: 'marketingStatus' }),
    f('gdprLegalBasis', 'GDPR legal basis', 'picklist', { options: ['Consent', 'Contract', 'Legitimate interest', 'Not applicable'] }),
    f('emailBounced', 'Email bounced', 'boolean', { computed: true }),
    f('emailBouncedReason', 'Email bounce reason', 'text', { computed: true }),
    f('doubleOptInStatus', 'Double opt-in status', 'picklist', { options: ['Pending', 'Confirmed', 'Not requested'] }),
  ]),
  ...sec('Engagement', [
    f('lastActivityAt', 'Last activity', 'datetime', { computed: true, defaultVisible: true }),
    f('lastContactedAt', 'Last contacted', 'datetime', { computed: true }),
    f('lastEngagedAt', 'Last engaged', 'datetime', { computed: true }),
    f('nextActivityAt', 'Next activity', 'datetime', { computed: true }),
    f('firstInteractionAt', 'First interaction', 'datetime', { computed: true }),
    f('connectionStrength', 'Connection strength', 'picklist', { options: ['Strong', 'Medium', 'Weak'], computed: true }),
    f('strongestConnectionUserId', 'Strongest connection', 'user', { computed: true }),
    f('activitiesCount', 'Activities count', 'number', { computed: true }),
    f('timesContactedCount', 'Times contacted', 'number', { computed: true }),
    f('emailsExchangedCount', 'Emails exchanged', 'number', { computed: true }),
    f('meetingsHeldCount', 'Meetings held', 'number', { computed: true }),
    f('leadResponseTime', 'Lead response time', 'duration', { computed: true }),
    f('originalSource', 'Original source', 'picklist', { picklist: 'leadSource', computed: true }),
    f('originalSourceDetail1', 'Original source detail 1', 'text', { computed: true }),
    f('originalSourceDetail2', 'Original source detail 2', 'text', { computed: true }),
    f('latestSource', 'Latest source', 'picklist', { picklist: 'leadSource', computed: true }),
    f('latestSourceDetail1', 'Latest source detail 1', 'text', { computed: true }),
    f('latestSourceAt', 'Latest source date', 'datetime', { computed: true }),
    f('pageViewsCount', 'Page views', 'number', { computed: true }),
    f('sessionsCount', 'Sessions', 'number', { computed: true }),
    f('firstPageSeen', 'First page seen', 'url', { computed: true }),
    f('firstReferrer', 'First referrer', 'url', { computed: true }),
    f('firstSeenAt', 'First seen', 'datetime', { computed: true }),
    f('lastSeenAt', 'Last seen', 'datetime', { computed: true }),
    f('formSubmissionsCount', 'Form submissions', 'number', { computed: true }),
    f('firstConversion', 'First conversion', 'text', { computed: true }),
    f('firstConversionAt', 'First conversion at', 'datetime', { computed: true }),
    f('recentConversion', 'Recent conversion', 'text', { computed: true }),
    f('recentConversionAt', 'Recent conversion at', 'datetime', { computed: true }),
    f('googleClickId', 'Google click id (gclid)', 'text', { computed: true }),
    f('facebookClickId', 'Facebook click id (fbclid)', 'text', { computed: true }),
    f('marketingEmailsDelivered', 'Marketing emails delivered', 'number', { computed: true }),
    f('marketingEmailsOpened', 'Marketing emails opened', 'number', { computed: true }),
    f('marketingEmailsClicked', 'Marketing emails clicked', 'number', { computed: true }),
    f('lastMarketingEmailAt', 'Last marketing email', 'datetime', { computed: true }),
    f('lastMeetingBookedAt', 'Last meeting booked', 'datetime', { computed: true }),
    f('lastNpsScore', 'Last NPS score', 'number', { computed: true }),
  ]),
  ...sec('Deal rollups', [
    f('dealsCount', 'Deals count', 'rollup', { computed: true }),
    f('openDealsCount', 'Open deals', 'rollup', { computed: true }),
    f('wonDealsCount', 'Won deals', 'rollup', { computed: true }),
    f('lostDealsCount', 'Lost deals', 'rollup', { computed: true }),
    f('totalRevenue', 'Total revenue', 'currency', { computed: true }),
    f('recentDealAmount', 'Recent deal amount', 'currency', { computed: true }),
    f('recentDealClosedAt', 'Recent deal closed', 'datetime', { computed: true }),
    f('firstDealCreatedAt', 'First deal created', 'datetime', { computed: true }),
    f('daysToClose', 'Days to close', 'number', { computed: true }),
  ]),
  ...sec('Sequence and automation', [
    f('activeSequenceId', 'Active sequence', 'link', { linkTarget: 'sequence', computed: true }),
    f('sequenceState', 'Sequence state', 'picklist', { options: ['Active', 'Paused', 'Completed', 'Exited'], computed: true }),
    f('sequencesEnrolledCount', 'Sequences enrolled', 'number', { computed: true }),
    f('lastSequenceEndedAt', 'Last sequence ended', 'datetime', { computed: true }),
  ]),
];
