// Canonical Deal field registry (spec Section 1.3 - 68 fields in 8 sections).
// Sub-objects (line items, stakeholders, competitors, close plan, history)
// stay in store-depth.js dealExtras; formalized in spec 1.3.1.
import { f, sec } from './util.js';

export const DEAL_FIELDS = [
  ...sec('Core', [
    f('name', 'Deal name', 'text', { required: true, defaultVisible: true }),
    f('companyId', 'Company', 'link', { linkTarget: 'company', defaultVisible: true }),
    f('primaryContactId', 'Primary contact', 'link', { linkTarget: 'contact' }),
    f('contactIds', 'Contacts', 'link', { linkTarget: 'contact', multi: true }),
    f('pipelineId', 'Pipeline', 'link', { linkTarget: 'pipeline' }),
    f('stage', 'Stage', 'status', { defaultVisible: true }),
    f('status', 'Status', 'picklist', { options: ['Open', 'Won', 'Lost'], computed: true }),
    f('probability', 'Probability', 'percent', { defaultVisible: true }),
    f('forecastCategory', 'Forecast category', 'picklist', { picklist: 'forecastCategory', defaultVisible: true }),
    f('closeDate', 'Close date', 'date', { defaultVisible: true }),
    f('ownerId', 'Owner', 'user', { defaultVisible: true }),
    f('description', 'Description', 'textarea'),
    f('dealType', 'Deal type', 'picklist', { picklist: 'dealType' }),
    f('leadSource', 'Lead source', 'picklist', { picklist: 'leadSource' }),
    f('campaignId', 'Campaign', 'link', { linkTarget: 'campaign' }),
    f('nextStep', 'Next step', 'text'),
    f('nextStepDueAt', 'Next step due', 'datetime'),
    f('priority', 'Priority', 'picklist', { options: ['High', 'Medium', 'Low'] }),
  ]),
  ...sec('Money', [
    f('amount', 'Amount', 'currency', { storeKey: 'value', defaultVisible: true }),
    f('currency', 'Currency', 'picklist', { options: ['USD', 'EUR', 'GBP', 'CAD', 'AUD'] }),
    f('exchangeRate', 'Exchange rate', 'number'),
    f('amountHome', 'Amount (home currency)', 'currency', { computed: true }),
    f('expectedRevenue', 'Expected revenue', 'currency', { computed: true }),
    f('acv', 'ACV', 'currency'),
    f('arr', 'ARR', 'currency'),
    f('mrr', 'MRR', 'currency'),
    f('tcv', 'TCV', 'currency', { computed: true }),
    f('oneTimeTotal', 'One-time total', 'currency', { computed: true }),
    f('recurringTotal', 'Recurring total', 'currency', { computed: true }),
    f('closedAmount', 'Closed amount', 'currency', { computed: true }),
    f('recurringRevenueType', 'Recurring revenue type', 'picklist', { options: ['New', 'Renewal', 'Upgrade', 'Downgrade'] }),
    f('recurringInactiveReason', 'Recurring inactive reason', 'picklist', { options: ['Churned', 'Paused', 'Migrated'] }),
    f('recurringInactiveAt', 'Recurring inactive at', 'datetime'),
    f('priceBookId', 'Price book', 'link', { linkTarget: 'priceBook' }),
  ]),
  ...sec('Health and AI', [
    f('dealScore', 'Deal score', 'number', { computed: true }),
    f('stalledAt', 'Stalled at', 'datetime', { computed: true }),
    f('rottingAt', 'Rotting at', 'datetime', { computed: true }),
    f('ageInDays', 'Age in days', 'number', { computed: true }),
    f('daysInStage', 'Days in stage', 'number', { computed: true }),
    f('stageEnteredAt', 'Stage entered at', 'datetime', { computed: true }),
    f('pushCount', 'Push count', 'number', { computed: true }),
    f('isSlipping', 'Slipping', 'boolean', { computed: true }),
    f('hasOverdueTask', 'Has overdue task', 'boolean', { computed: true }),
    f('aiSummary', 'AI summary', 'textarea', { computed: true }),
  ]),
  ...sec('Team and splits', [
    f('teamMembers', 'Team members', 'sublist'),
    f('collaboratorIds', 'Collaborators', 'user', { multi: true }),
    f('splits', 'Splits', 'sublist'),
    f('followerIds', 'Followers', 'user', { multi: true }),
  ]),
  ...sec('Outcome', [
    f('wonAt', 'Won at', 'datetime', { computed: true }),
    f('lostAt', 'Lost at', 'datetime', { computed: true }),
    f('winReason', 'Win reason', 'picklist', { picklist: 'winReason' }),
    f('lossReason', 'Loss reason', 'picklist', { picklist: 'lossReason' }),
    f('lostToCompetitor', 'Lost to competitor', 'text'),
  ]),
  ...sec('Relations', [
    f('primaryQuoteId', 'Primary quote', 'link', { linkTarget: 'quote' }),
    f('contractId', 'Contract', 'link', { linkTarget: 'contract' }),
    f('territoryId', 'Territory', 'link', { linkTarget: 'territory' }),
  ]),
  ...sec('Engagement', [
    f('lastActivityAt', 'Last activity', 'datetime', { computed: true }),
    f('lastContactedAt', 'Last contacted', 'datetime', { computed: true }),
    f('nextActivityAt', 'Next activity', 'datetime', { computed: true }),
    f('activitiesCount', 'Activities count', 'number', { computed: true }),
    f('doneActivitiesCount', 'Done activities', 'number', { computed: true }),
    f('timesContactedCount', 'Times contacted', 'number', { computed: true }),
    f('emailsExchangedCount', 'Emails exchanged', 'number', { computed: true }),
    f('nextMeetingAt', 'Next meeting', 'datetime', { computed: true }),
  ]),
  ...sec('System', [
    f('tags', 'Tags', 'tags'),
    f('visibility', 'Visibility', 'picklist', { picklist: 'visibility' }),
    f('approvalStatus', 'Approval status', 'picklist', { options: ['None', 'Pending', 'Approved', 'Rejected'] }),
    f('originatedFrom', 'Originated from', 'picklist', { options: ['Lead qualify', 'API', 'Import', 'Form', 'Chat', 'Manual'] }),
  ]),
];
